import mysql.connector

def seed_db():
    conn = mysql.connector.connect(
        host="localhost",
        user="root",
        password="",
        database="drugssearch"
    )
    cursor = conn.cursor()

    # Clear existing data to avoid duplicates
    cursor.execute("TRUNCATE TABLE lab_parameters")

    data = [
        # ===== ANTIOXIDANT PANEL =====
        ("Serum Coenzyme Q10", 0.5, 1.5, "µg/mL", "Antioxidant Panel",
         "Mitochondrial Dysfunction", "Supplement Therapy", "CoQ10 Capsules, Multivitamins"),
        ("Serum Glutathione", 500.0, 1200.0, "µmol/L", "Antioxidant Panel",
         "Oxidative Stress", "Antioxidants", "Vitamin C, Vitamin E, NAC"),

        # ===== AUTOIMMUNE PANEL =====
        ("Anti-dsDNA", 0.0, 30.0, "IU/mL", "Autoimmune Panel",
         "Lupus", "Immunosuppressants", "Azathioprine, Hydroxychloroquine, Prednisone"),
        ("Serum Anti-CCP", 0.0, 20.0, "U/mL", "Autoimmune Panel",
         "Rheumatoid Arthritis", "DMARDs", "Methotrexate, Sulfasalazine, Leflunomide"),
        ("Serum Anti-Nuclear Antibody", 0.0, 1.0, "Index", "Autoimmune Panel",
         "Autoimmune Disease", "Immunosuppressants", "Methotrexate, Prednisolone, Azathioprine"),
        ("Serum Anti-RNP", 0.0, 20.0, "U/mL", "Autoimmune Panel",
         "Mixed Connective Tissue Disease", "Immunotherapy", "Methotrexate, Prednisolone"),
        ("Serum Anti-Smith Antibody", 0.0, 20.0, "U/mL", "Autoimmune Panel",
         "Lupus", "Immunosuppressants", "Azathioprine, Hydroxychloroquine, Prednisone"),
        ("Serum Cardiolipin Antibody", 0.0, 12.0, "GPL Units", "Autoimmune Panel",
         "Antiphospholipid Syndrome", "Anticoagulants", "Warfarin, Heparin, Aspirin"),
        ("Serum Rheumatoid Factor", 0.0, 14.0, "IU/mL", "Autoimmune Panel",
         "Rheumatoid Arthritis", "Anti-inflammatory Drugs", "Methotrexate, Prednisone, Hydroxychloroquine"),

        # ===== BLOOD COUNT =====
        ("Basophils", 0.0, 1.0, "%", "Blood Count",
         "Allergic Reaction or Myeloproliferative Disorder (if high)", "Antihistamines", "Cetirizine, Loratadine"),
        ("Basophils", 0.0, 2.0, "%", "Blood Count",
         "Inflammatory Condition", "Anti-allergy Drugs", "Levocetirizine"),
        ("Eosinophils", 0.0, 6.0, "%", "Blood Count",
         "Allergy or Parasitic Infection (if high)", "Antihistamines/Antiparasitics", "Cetirizine, Albendazole"),
        ("Eosinophils", 1.0, 6.0, "%", "Blood Count",
         "Allergic Reaction", "Antihistamines", "Cetirizine, Loratadine"),
        ("ESR", 0.0, 20.0, "mm/hr", "Blood Count",
         "Inflammation or Infection (if high)", "Anti-inflammatory", "Ibuprofen, Naproxen"),
        ("Hematocrit", 36.0, 54.0, "%", "Blood Count",
         "Dehydration (High) or Anemia (Low)", "Fluids/Iron", "IV Fluids, Iron Supplements"),
        ("Hemoglobin", 13.0, 17.5, "g/dL", "Blood Count",
         "Anemia (if low) or Polycythemia (if high)", "Supplements", "Iron Supplements, Vitamin B12"),
        ("Lymphocytes", 20.0, 45.0, "%", "Blood Count",
         "Viral Infection (High) or Immunodeficiency (Low)", "Antivirals/Immunotherapy", "Acyclovir, Consult Immunologist"),
        ("Lymphocytes", 20.0, 40.0, "%", "Blood Count",
         "Lymphocytosis", "Antivirals", "Acyclovir, Oseltamivir"),
        ("MCH", 27.0, 32.0, "pg", "Blood Count",
         "Hypochromic Anemia (Low) or Macrocytic Anemia (High)", "Vitamins", "Iron Supplements, Vitamin B12"),
        ("MCHC", 32.0, 36.0, "g/dL", "Blood Count",
         "Hypochromic Anemia (Low) or Spherocytosis (High)", "Iron/Supplements", "Iron Supplements, Folic Acid"),
        ("MCV", 80.0, 100.0, "fL", "Blood Count",
         "Macrocytic Anemia (High) or Microcytic Anemia (Low)", "Vitamins", "Vitamin B12, Folic Acid, Iron"),
        ("Mean Platelet Volume", 7.5, 11.5, "fL", "Blood Count",
         "Platelet Disorder", "Antiplatelet / Supportive Therapy", "Aspirin, Clopidogrel, Ticagrelor"),
        ("Monocytes", 2.0, 10.0, "%", "Blood Count",
         "Chronic Infection or Inflammation (if high)", "Anti-inflammatory", "Consult Physician"),
        ("Monocytes", 2.0, 8.0, "%", "Blood Count",
         "Monocytosis", "Anti-inflammatory Drugs", "Prednisolone"),
        ("Neutrophils", 40.0, 75.0, "%", "Blood Count",
         "Bacterial Infection (High) or Neutropenia (Low)", "Antibiotics", "Ciprofloxacin, Ceftriaxone"),
        ("Neutrophils", 40.0, 70.0, "%", "Blood Count",
         "Neutropenia / Infection", "Antibiotics", "Amoxicillin, Cefixime"),
        ("PCV", 36.0, 54.0, "%", "Blood Count",
         "Polycythemia (High) or Anemia (Low)", "Iron/Supplements", "Iron Supplements, Folic Acid"),
        ("Platelets", 150000.0, 450000.0, "platelets/mcL", "Blood Count",
         "Clotting disorder risk", "Platelet Support", "Consult Hematologist"),
        ("Polymorphs", 40.0, 75.0, "%", "Blood Count",
         "Bacterial Infection (High) or Neutropenia (Low)", "Antibiotics", "Ciprofloxacin, Ceftriaxone"),
        ("RBC", 4.0, 5.9, "million/mcL", "Blood Count",
         "Anemia (Low) or Erythrocytosis (High)", "Vitamins", "Iron, Folic Acid"),
        ("Red Cell Distribution Width", 11.5, 14.5, "%", "Blood Count",
         "Anemia Variants", "Iron / Vitamin Therapy", "Ferrous Sulfate, Vitamin B12, Folic Acid"),
        ("Reticulocyte Count", 0.5, 2.5, "%", "Blood Count",
         "Bone Marrow Dysfunction", "Hematopoietic Agents", "Erythropoietin, Iron Sucrose, Cyanocobalamin"),
        ("Total Count", 4000.0, 11000.0, "cells/cumm", "Blood Count",
         "Leukocytosis (High) or Leukopenia (Low)", "Antibiotics/Immunostimulants", "Amoxicillin, Filgrastim"),
        ("WBC", 4500.0, 11000.0, "cells/mcL", "Blood Count",
         "Infection (High) or Immune deficiency (Low)", "Antibiotics/Antivirals", "Amoxicillin, Acyclovir (consult doctor)"),

        # ===== BLOOD PANEL =====
        ("Serum Haptoglobin", 30.0, 200.0, "mg/dL", "Blood Panel",
         "Hemolytic Anemia", "Supportive Therapy", "Folic Acid, Iron Supplements"),

        # ===== BONE PANEL =====
        ("NTX (Bone Marker)", 6.0, 19.0, "nmol BCE/mmol creatinine", "Bone Panel",
         "Osteoporosis", "Bisphosphonates", "Alendronate, Risedronate"),
        ("Osteocalcin", 11.0, 43.0, "ng/mL", "Bone Panel",
         "Bone Turnover Disorder", "Vitamin D Therapy", "Cholecalciferol, Calcium Supplements"),
        ("Serum Osteopontin", 0.0, 50.0, "ng/mL", "Bone Panel",
         "Bone Disorder", "Bisphosphonates", "Alendronate, Zoledronic Acid"),
        ("Serum Phosphatase (Bone Specific)", 15.0, 41.0, "U/L", "Bone Panel",
         "Bone Disease", "Bisphosphonates", "Alendronate, Ibandronate, Risedronate"),

        # ===== CARDIAC MARKER =====
        ("High Sensitivity CRP", 0.0, 1.0, "mg/L", "Cardiac Marker",
         "Cardiovascular Risk", "Statins", "Atorvastatin, Rosuvastatin, Simvastatin"),
        ("Homocysteine", 5.0, 15.0, "µmol/L", "Cardiac Marker",
         "Cardiovascular Risk", "Vitamin Therapy", "Folic Acid, Vitamin B6, Vitamin B12"),
        ("Serum BNP", 0.0, 100.0, "pg/mL", "Cardiac Marker",
         "Heart Failure", "Diuretics", "Furosemide, Spironolactone"),
        ("Serum Creatinine Kinase MB Fraction", 0.0, 5.0, "ng/mL", "Cardiac Marker",
         "Heart Attack", "Cardiac Therapy", "Aspirin, Clopidogrel, Metoprolol"),
        ("Serum Troponin C", 0.0, 0.05, "ng/mL", "Cardiac Marker",
         "Cardiac Injury", "Cardiac Therapy", "Aspirin, Nitroglycerin, Beta Blockers"),
        ("Serum Troponin T", 0.0, 0.01, "ng/mL", "Cardiac Marker",
         "Myocardial Infarction", "Cardiac Therapy", "Aspirin, Clopidogrel, Nitroglycerin"),

        # ===== CARDIAC MARKERS =====
        ("CK-MB", 0.0, 5.0, "ng/mL", "Cardiac Markers",
         "Heart Damage", "Beta Blockers", "Metoprolol"),
        ("NT-proBNP", 0.0, 125.0, "pg/mL", "Cardiac Markers",
         "Heart Failure", "Diuretics", "Furosemide"),
        ("Serum Creatine Kinase", 30.0, 200.0, "U/L", "Cardiac Markers",
         "Muscle Damage", "Cardiac Therapy", "Aspirin, Beta Blockers"),
        ("Serum Myoglobin", 0.0, 85.0, "ng/mL", "Cardiac Markers",
         "Muscle Injury", "Cardiac Support Therapy", "Aspirin, Clopidogrel, Metoprolol"),
        ("Troponin I", 0.0, 0.04, "ng/mL", "Cardiac Markers",
         "Myocardial Infarction", "Antiplatelets", "Aspirin, Clopidogrel"),

        # ===== COAGULATION PANEL =====
        ("Activated Partial Thromboplastin Time", 25.0, 35.0, "seconds", "Coagulation Panel",
         "Clotting Disorder", "Anticoagulants", "Heparin, Warfarin, Apixaban"),
        ("D-Dimer", 0.0, 0.5, "µg/mL", "Coagulation Panel",
         "Thrombosis", "Anticoagulants", "Heparin"),
        ("Fibrinogen", 200.0, 400.0, "mg/dL", "Coagulation Panel",
         "Clotting Risk", "Anticoagulants", "Warfarin, Dabigatran, Rivaroxaban"),
        ("INR", 0.8, 1.2, "Ratio", "Coagulation Panel",
         "Clotting Disorder", "Anticoagulants", "Warfarin"),
        ("Prothrombin Time", 11.0, 13.5, "seconds", "Coagulation Panel",
         "Bleeding Disorder", "Anticoagulants", "Warfarin"),

        # ===== DIABETES PANEL =====
        ("Fasting Insulin", 2.0, 25.0, "µIU/mL", "Diabetes Panel",
         "Insulin Resistance", "Antidiabetic Drugs", "Metformin"),
        ("HbA1c", 4.0, 5.6, "%", "Diabetes Panel",
         "Diabetes Mellitus", "Antidiabetic Drugs", "Metformin"),
        ("Insulin Resistance Index (HOMA-IR)", 0.5, 2.5, "Index", "Diabetes Panel",
         "Insulin Resistance", "Antidiabetic Drugs", "Metformin, Pioglitazone, Sitagliptin"),
        ("Postprandial Glucose", 70.0, 140.0, "mg/dL", "Diabetes Panel",
         "Diabetes Mellitus", "Antidiabetic Drugs", "Glimepiride"),
        ("Random Blood Glucose", 70.0, 140.0, "mg/dL", "Diabetes Panel",
         "Diabetes Mellitus", "Antidiabetic Drugs", "Metformin, Glimepiride, Insulin"),
        ("Serum Anti-Insulin Antibody", 0.0, 10.0, "U/mL", "Diabetes Panel",
         "Type 1 Diabetes", "Insulin Therapy", "Regular Insulin, Glargine"),
        ("Serum Beta-Hydroxybutyrate", 0.0, 0.6, "mmol/L", "Diabetes Panel",
         "Ketoacidosis", "Insulin Therapy", "Regular Insulin"),
        ("Serum C-Peptide", 0.5, 2.0, "ng/mL", "Diabetes Panel",
         "Insulin Production Disorder", "Antidiabetic Drugs", "Insulin, Metformin, Sulfonylureas"),
        ("Serum Ketones", 0.0, 0.6, "mmol/L", "Diabetes Panel",
         "Diabetic Ketoacidosis", "Insulin Therapy", "Regular Insulin, IV Fluids"),

        # ===== DRUG MONITORING =====
        ("Serum Cyclosporine Level", 100.0, 400.0, "ng/mL", "Drug Monitoring",
         "Transplant Monitoring", "Immunosuppressants", "Cyclosporine, Tacrolimus"),
        ("Serum Digoxin Level", 0.5, 2.0, "ng/mL", "Drug Monitoring",
         "Cardiac Arrhythmia", "Cardiac Drugs", "Digoxin"),
        ("Serum Lithium Level", 0.6, 1.2, "mEq/L", "Drug Monitoring",
         "Bipolar Disorder", "Mood Stabilizers", "Lithium Carbonate"),
        ("Serum Phenytoin Level", 10.0, 20.0, "µg/mL", "Drug Monitoring",
         "Epilepsy", "Antiepileptics", "Phenytoin, Carbamazepine, Valproate"),
        ("Serum Tacrolimus Level", 5.0, 20.0, "ng/mL", "Drug Monitoring",
         "Transplant Rejection", "Immunosuppressants", "Tacrolimus, Cyclosporine"),
        ("Serum Theophylline Level", 5.0, 15.0, "µg/mL", "Drug Monitoring",
         "Asthma", "Bronchodilators", "Theophylline"),

        # ===== ELECTROLYTES =====
        ("Ionized Calcium", 4.5, 5.6, "mg/dL", "Electrolytes",
         "Hypocalcemia", "Calcium Therapy", "Calcium Gluconate, Vitamin D3, Calcitonin"),
        ("Serum Bicarbonate", 22.0, 29.0, "mmol/L", "Electrolytes",
         "Metabolic Acidosis", "Alkalinizing Agents", "Sodium Bicarbonate, IV Fluids"),
        ("Serum Calcium", 8.6, 10.2, "mg/dL", "Electrolytes",
         "Hypocalcemia", "Calcium Supplements", "Calcium Carbonate"),
        ("Serum Chloride", 96.0, 106.0, "mmol/L", "Electrolytes",
         "Electrolyte Imbalance", "IV Fluids", "Ringer Lactate"),
        ("Serum Chloride/Bicarbonate Ratio", 0.8, 1.2, "Ratio", "Electrolytes",
         "Acid Base Disorder", "Alkalinizing Agents", "Sodium Bicarbonate, IV Fluids"),
        ("Serum Magnesium", 1.7, 2.2, "mg/dL", "Electrolytes",
         "Magnesium Deficiency", "Magnesium Supplements", "Magnesium Oxide"),
        ("Serum Osmolality", 275.0, 295.0, "mOsm/kg", "Electrolytes",
         "Fluid Imbalance", "IV Fluids", "Normal Saline, Dextrose Saline, Ringer Lactate"),
        ("Serum Phosphate", 2.5, 4.5, "mg/dL", "Electrolytes",
         "Phosphate Imbalance", "Phosphate Binders", "Sevelamer"),
        ("Serum Potassium", 3.5, 5.0, "mmol/L", "Electrolytes",
         "Hyperkalemia", "Potassium Binders", "Kayexalate"),
        ("Serum Sodium", 135.0, 145.0, "mmol/L", "Electrolytes",
         "Hyponatremia", "IV Saline", "Normal Saline"),

        # ===== GENERAL PANEL =====
        ("LDH", 140.0, 280.0, "U/L", "General Panel",
         "Tissue Damage", "Supportive Therapy", "Vitamin Supplements"),
        ("Serum Lactate Dehydrogenase Isoenzyme", 100.0, 250.0, "U/L", "General Panel",
         "Tissue Damage", "Supportive Therapy", "Vitamin C, Antioxidants"),

        # ===== GENETIC PANEL =====
        ("Serum Alpha-1 Antitrypsin", 90.0, 200.0, "mg/dL", "Genetic Panel",
         "Liver Disease", "Supportive Therapy", "Alpha-1 Replacement Therapy"),

        # ===== HORMONAL PANEL =====
        ("Beta-HCG", 0.0, 5.0, "mIU/mL", "Hormonal Panel",
         "Pregnancy / Tumor Marker", "Hormonal Monitoring", "Progesterone Support"),
        ("DHEA-S", 35.0, 430.0, "µg/dL", "Hormonal Panel",
         "Adrenal Disorder", "Hormone Therapy", "DHEA Supplements"),
        ("Estradiol", 15.0, 350.0, "pg/mL", "Hormonal Panel",
         "Estrogen Imbalance", "Hormone Therapy", "Estradiol Valerate, Conjugated Estrogen"),
        ("Growth Hormone", 0.0, 5.0, "ng/mL", "Hormonal Panel",
         "Growth Disorder", "Hormone Therapy", "Somatropin, Octreotide"),
        ("Parathyroid Hormone", 10.0, 65.0, "pg/mL", "Hormonal Panel",
         "Hyperparathyroidism", "Calcium Regulation Drugs", "Calcitriol, Cinacalcet"),
        ("Plasma Renin Activity", 0.6, 4.3, "ng/mL/hr", "Hormonal Panel",
         "Hypertension", "ACE Inhibitors", "Ramipril, Enalapril, Lisinopril"),
        ("Progesterone", 0.1, 20.0, "ng/mL", "Hormonal Panel",
         "Hormonal Disorder", "Progesterone Therapy", "Medroxyprogesterone, Micronized Progesterone"),
        ("Prolactin", 4.0, 23.0, "ng/mL", "Hormonal Panel",
         "Hormonal Imbalance", "Dopamine Agonists", "Cabergoline"),
        ("PSA", 0.0, 4.0, "ng/mL", "Hormonal Panel",
         "Prostate Disorder", "Alpha Blockers", "Tamsulosin"),
        ("Serum ACTH", 10.0, 60.0, "pg/mL", "Hormonal Panel",
         "Adrenal Disorder", "Corticosteroids", "Hydrocortisone, Prednisolone, Dexamethasone"),
        ("Serum Aldosterone", 4.0, 31.0, "ng/dL", "Hormonal Panel",
         "Hypertension", "Antihypertensives", "Spironolactone, Eplerenone, ACE Inhibitors"),
        ("Serum Androstenedione", 0.3, 3.5, "ng/mL", "Hormonal Panel",
         "PCOS / Adrenal Disorder", "Hormonal Therapy", "Oral Contraceptives, Metformin, Spironolactone"),
        ("Serum Anti-Mullerian Hormone", 1.0, 4.0, "ng/mL", "Hormonal Panel",
         "Infertility", "Fertility Therapy", "Clomiphene, Letrozole, Gonadotropins"),
        ("Serum Calcitonin", 0.0, 10.0, "pg/mL", "Hormonal Panel",
         "Thyroid Cancer Risk", "Oncology Drugs", "Cabozantinib, Vandetanib"),
        ("Serum Cortisol", 6.0, 23.0, "µg/dL", "Hormonal Panel",
         "Adrenal Disorder", "Corticosteroids", "Hydrocortisone, Prednisone, Dexamethasone"),
        ("Serum Erythropoietin", 4.0, 27.0, "mIU/mL", "Hormonal Panel",
         "Anemia", "Erythropoiesis Agents", "Erythropoietin Injection, Iron Supplements"),
        ("Serum Free Testosterone", 5.0, 25.0, "pg/mL", "Hormonal Panel",
         "Hormonal Imbalance", "Hormone Therapy", "Testosterone Gel, Clomiphene, Anastrozole"),
        ("Serum IGF-1", 90.0, 360.0, "ng/mL", "Hormonal Panel",
         "Growth Disorder", "Hormone Therapy", "Somatropin, Octreotide"),
        ("Serum Prolactin (Male)", 4.0, 15.0, "ng/mL", "Hormonal Panel",
         "Hyperprolactinemia", "Dopamine Agonists", "Cabergoline, Bromocriptine"),
        ("Serum Renin", 0.2, 3.3, "ng/mL/hr", "Hormonal Panel",
         "Renal Hypertension", "ACE Inhibitors", "Ramipril, Enalapril, Losartan"),
        ("Serum SHBG", 20.0, 60.0, "nmol/L", "Hormonal Panel",
         "Hormonal Imbalance", "Hormone Therapy", "Clomiphene, Hormonal Pills"),
        ("Serum Total Testosterone (Female)", 15.0, 70.0, "ng/dL", "Hormonal Panel",
         "PCOS", "Hormonal Therapy", "Metformin, Oral Contraceptives"),
        ("Testosterone", 300.0, 1000.0, "ng/dL", "Hormonal Panel",
         "Hormonal Deficiency", "Hormone Therapy", "Testosterone Gel, Testosterone Injection, Clomiphene"),

        # ===== IMMUNE PANEL =====
        ("Serum Complement C3", 90.0, 180.0, "mg/dL", "Immune Panel",
         "Immune Disorder", "Immunosuppressants", "Azathioprine, Mycophenolate"),
        ("Serum Complement C4", 10.0, 40.0, "mg/dL", "Immune Panel",
         "Autoimmune Disorder", "Immunotherapy", "Cyclophosphamide, Prednisolone"),
        ("Serum Interferon Gamma", 0.0, 15.0, "pg/mL", "Immune Panel",
         "Immune Activation", "Immunomodulators", "Interferon Therapy, Steroids"),

        # ===== IMMUNOLOGY =====
        ("RA Factor", 0.0, 20.0, "IU/mL", "Immunology",
         "Rheumatoid Arthritis (if high)", "DMARDs", "Methotrexate, Hydroxychloroquine"),

        # ===== IMMUNOLOGY PANEL =====
        ("Serum Anti-HBs", 10.0, 1000.0, "mIU/mL", "Immunology Panel",
         "Hepatitis B Immunity", "Vaccination", "Hepatitis B Vaccine"),
        ("Serum Anti-HCV", 0.0, 1.0, "Index", "Immunology Panel",
         "Hepatitis C", "Antivirals", "Sofosbuvir, Ribavirin"),
        ("Serum Anti-HIV", 0.0, 1.0, "Index", "Immunology Panel",
         "HIV Infection", "Antiretrovirals", "Tenofovir, Lamivudine, Dolutegravir"),

        # ===== INFECTION MARKER =====
        ("Serum Procalcitonin", 0.0, 0.1, "ng/mL", "Infection Marker",
         "Sepsis", "Antibiotics", "Meropenem, Piperacillin-Tazobactam"),

        # ===== INFLAMMATORY MARKER =====
        ("Serum Calprotectin", 0.0, 50.0, "µg/g", "Inflammatory Marker",
         "IBD", "Immunotherapy", "Infliximab, Adalimumab"),
        ("Serum Interleukin-6", 0.0, 7.0, "pg/mL", "Inflammatory Marker",
         "Cytokine Storm", "Immunotherapy", "Tocilizumab, Steroids"),
        ("Serum Lactoferrin", 0.0, 7.0, "µg/mL", "Inflammatory Marker",
         "Intestinal Inflammation", "Anti-inflammatory Drugs", "Mesalamine, Steroids"),

        # ===== INFLAMMATORY MARKERS =====
        ("C-Reactive Protein", 0.0, 3.0, "mg/L", "Inflammatory Markers",
         "Inflammation", "NSAIDs", "Ibuprofen"),
        ("ESR", 0.0, 20.0, "mm/hr", "Inflammatory Markers",
         "Chronic Inflammation", "Steroids", "Prednisolone"),

        # ===== IRON STUDIES =====
        ("Ferritin", 12.0, 300.0, "ng/mL", "Iron Studies",
         "Iron Deficiency", "Iron Supplements", "Ferrous Sulfate"),
        ("Serum Ferric Binding Capacity", 240.0, 450.0, "µg/dL", "Iron Studies",
         "Iron Deficiency", "Iron Supplements", "Ferrous Sulfate, Iron Sucrose"),
        ("Serum Ferric Index", 20.0, 50.0, "%", "Iron Studies",
         "Iron Imbalance", "Iron Therapy", "Ferrous Sulfate, Ferric Carboxymaltose"),
        ("Serum Ferric Saturation", 20.0, 50.0, "%", "Iron Studies",
         "Iron Overload", "Chelation Therapy", "Deferoxamine, Deferasirox"),
        ("Serum Iron", 60.0, 170.0, "µg/dL", "Iron Studies",
         "Iron Deficiency", "Iron Supplements", "Ferrous Ascorbate"),
        ("Serum Transferrin", 200.0, 360.0, "mg/dL", "Iron Studies",
         "Iron Deficiency", "Iron Therapy", "Ferrous Sulfate, Ferrous Gluconate, Iron Sucrose"),
        ("TIBC", 240.0, 450.0, "µg/dL", "Iron Studies",
         "Iron Deficiency Anemia", "Iron Therapy", "Ferrous Gluconate"),
        ("Transferrin Saturation", 20.0, 50.0, "%", "Iron Studies",
         "Iron Overload", "Chelation Therapy", "Deferoxamine, Deferasirox, Penicillamine"),

        # ===== KIDNEY FUNCTION =====
        ("Blood Urea", 10.0, 50.0, "mg/dL", "Kidney Function",
         "Kidney Dysfunction (High) or Liver Disease (Low)", "Kidney Support", "Consult Nephrologist"),
        ("BUN", 7.0, 20.0, "mg/dL", "Kidney Function",
         "Kidney issue or Dehydration", "Kidney Support", "Hydration"),
        ("BUN/Creatinine Ratio", 10.0, 20.0, "Ratio", "Kidney Function",
         "Renal Dysfunction", "Diuretics", "Furosemide"),
        ("Creatinine", 0.4, 1.3, "mg/dL", "Kidney Function",
         "Kidney Dysfunction", "Kidney Support", "Consult Nephrologist"),
        ("Cystatin C", 0.6, 1.2, "mg/L", "Kidney Function",
         "Kidney Dysfunction", "ACE Inhibitors", "Enalapril"),
        ("eGFR", 90.0, 200.0, "mL/min", "Kidney Function",
         "Kidney Disease (if low)", "Kidney Support", "Manage underlying conditions"),
        ("Serum Beta-Trace Protein", 0.5, 1.5, "mg/L", "Kidney Function",
         "Renal Dysfunction", "Nephroprotective Therapy", "ACE Inhibitors, Diuretics"),
        ("Serum Creatinine Clearance", 90.0, 140.0, "mL/min", "Kidney Function",
         "Renal Impairment", "Nephroprotective Drugs", "ACE Inhibitors, ARBs, Diuretics"),
        ("Serum Microalbumin", 0.0, 30.0, "mg/day", "Kidney Function",
         "Diabetic Nephropathy", "ACE Inhibitors", "Ramipril, Losartan, Enalapril"),
        ("Serum Urea Nitrogen", 7.0, 20.0, "mg/dL", "Kidney Function",
         "Renal Dysfunction", "Diuretics", "Furosemide, Spironolactone"),

        # ===== LIPID PROFILE =====
        ("Apolipoprotein B", 55.0, 125.0, "mg/dL", "Lipid Profile",
         "Atherosclerosis Risk", "Statins", "Rosuvastatin"),
        ("Direct LDL", 0.0, 100.0, "mg/dL", "Lipid Profile",
         "Hyperlipidemia", "Statins", "Atorvastatin, Rosuvastatin, Pravastatin"),
        ("HDL Cholesterol", 35.0, 60.0, "mg/dL", "Lipid Profile",
         "Risk of heart disease (if low)", "Lifestyle", "Niacin, Omega-3"),
        ("HDL Ratio", 1.0, 3.5, "Ratio", "Lipid Profile",
         "Dyslipidemia", "Statins / Lifestyle Therapy", "Atorvastatin, Niacin, Omega-3"),
        ("LDL Cholesterol", 0.0, 100.0, "mg/dL", "Lipid Profile",
         "High risk of atherosclerosis", "Statins", "Rosuvastatin, Pravastatin"),
        ("LDL/HDL Ratio", 1.0, 3.6, "", "Lipid Profile",
         "High cardiovascular risk (if high)", "Lifestyle", "Consult Cardiologist"),
        ("Lipoprotein (a)", 0.0, 30.0, "mg/dL", "Lipid Profile",
         "Genetic Heart Risk", "Lipid Lowering Therapy", "Niacin, PCSK9 Inhibitors"),
        ("Non-HDL Cholesterol", 0.0, 130.0, "mg/dL", "Lipid Profile",
         "High Cardiovascular Risk", "Statins", "Simvastatin"),
        ("Serum Apolipoprotein A1", 110.0, 180.0, "mg/dL", "Lipid Profile",
         "Low HDL", "Lipid Therapy", "Niacin, Statins, Omega-3"),
        ("Serum Lipoprotein Lipase", 5.0, 30.0, "U/L", "Lipid Profile",
         "Hypertriglyceridemia", "Lipid Lowering Drugs", "Fenofibrate, Gemfibrozil, Omega-3"),
        ("Serum Lipoprotein X", 0.0, 20.0, "mg/dL", "Lipid Profile",
         "Cholestasis", "Lipid Lowering Drugs", "Statins, Ursodeoxycholic Acid"),
        ("Small Dense LDL", 0.0, 30.0, "mg/dL", "Lipid Profile",
         "Atherosclerosis Risk", "Lipid Lowering Drugs", "Rosuvastatin, Ezetimibe, Fenofibrate"),
        ("T-Chol/HDL Ratio", 3.3, 5.0, "", "Lipid Profile",
         "High cardiovascular risk (if high)", "Lifestyle", "Consult Cardiologist"),
        ("Total Cholesterol", 0.0, 200.0, "mg/dL", "Lipid Profile",
         "Hypercholesterolemia", "Statins", "Atorvastatin, Simvastatin"),
        ("Triglycerides", 0.0, 150.0, "mg/dL", "Lipid Profile",
         "Risk of metabolic syndrome", "Fibrates", "Fenofibrate, Gemfibrozil"),
        ("VLDL Cholesterol", 5.0, 40.0, "mg/dL", "Lipid Profile",
         "Hyperlipidemia", "Statins", "Atorvastatin, Rosuvastatin"),

        # ===== LIVER FUNCTION =====
        ("A/G Ratio", 1.0, 2.5, "Ratio", "Liver Function",
         "Liver Disease", "Hepatic Therapy", "Silymarin"),
        ("Alkaline Phosphatase", 44.0, 147.0, "U/L", "Liver Function",
         "Liver or Bone Disorder", "Vitamin D Supplements", "Cholecalciferol"),
        ("Direct Bilirubin", 0.0, 0.3, "mg/dL", "Liver Function",
         "Biliary Obstruction", "Hepatic Drugs", "Ursodiol"),
        ("Gamma GT", 9.0, 48.0, "U/L", "Liver Function",
         "Liver Damage", "Hepatoprotective Drugs", "Silymarin"),
        ("Globulin", 2.0, 3.5, "g/dL", "Liver Function",
         "Immune Disorder", "Immunomodulators", "Azathioprine"),
        ("Indirect Bilirubin", 0.2, 0.8, "mg/dL", "Liver Function",
         "Hemolysis", "Supportive Therapy", "Folic Acid"),
        ("Serum Albumin", 3.5, 5.0, "g/dL", "Liver Function",
         "Malnutrition", "Nutritional Supplements", "Albumin Infusion"),
        ("Serum Ammonia", 15.0, 45.0, "µg/dL", "Liver Function",
         "Hepatic Encephalopathy", "Hepatic Drugs", "Lactulose, Rifaximin, Neomycin"),
        ("Serum Ammonium", 15.0, 45.0, "µmol/L", "Liver Function",
         "Hepatic Encephalopathy", "Hepatic Therapy", "Lactulose, Rifaximin"),
        ("Serum Globulin Ratio", 1.0, 2.2, "Ratio", "Liver Function",
         "Immune Dysfunction", "Immunomodulators", "Azathioprine, Methotrexate, Prednisolone"),
        ("Total Bilirubin", 0.2, 1.2, "mg/dL", "Liver Function",
         "Jaundice", "Hepatoprotective Drugs", "Ursodeoxycholic Acid"),
        ("Total Protein", 6.0, 8.3, "g/dL", "Liver Function",
         "Protein Imbalance", "Nutritional Supplements", "Albumin Infusion, Multivitamins, Amino Acid Supplements"),

        # ===== METABOLIC PANEL =====
        ("Calcium", 8.6, 10.3, "mg/dL", "Metabolic Panel",
         "Hypocalcemia (Low) or Hypercalcemia (High)", "Calcium/Vitamin D", "Calcium Carbonate, Calcitriol"),
        ("Glucose", 70.0, 110.0, "mg/dL", "Metabolic Panel",
         "Diabetes (High) or Hypoglycemia (Low)", "Antidiabetics", "Metformin, Insulin"),
        ("Potassium", 3.5, 5.2, "mmol/L", "Metabolic Panel",
         "Hypokalemia (Low) or Hyperkalemia (High)", "Potassium Supplements", "Potassium Chloride"),
        ("Serum Cystine", 0.3, 1.0, "mg/dL", "Metabolic Panel",
         "Cystinuria", "Chelation Therapy", "Penicillamine, Tiopronin"),
        ("Serum Lactate", 0.5, 2.2, "mmol/L", "Metabolic Panel",
         "Lactic Acidosis", "IV Fluids", "Ringer Lactate"),
        ("Serum Lactate", 0.5, 2.2, "mmol/L", "Metabolic Panel",
         "Lactic Acidosis", "IV Fluids", "Normal Saline, Sodium Bicarbonate"),
        ("Serum Pyruvate", 0.03, 0.1, "mmol/L", "Metabolic Panel",
         "Metabolic Disorder", "Vitamin Therapy", "Thiamine, Multivitamins"),
        ("Sodium", 135.0, 145.0, "mEq/L", "Metabolic Panel",
         "Hyponatremia (Low) or Hypernatremia (High)", "Electrolytes", "Salt Tablets, IV Fluids"),
        ("Uric Acid", 3.5, 7.2, "mg/dL", "Metabolic Panel",
         "Gout", "Uric Acid Reducers", "Allopurinol"),

        # ===== PANCREATIC PANEL =====
        ("Amylase", 30.0, 110.0, "U/L", "Pancreatic Panel",
         "Pancreatitis", "Digestive Enzymes", "Pancrelipase"),
        ("Lipase", 0.0, 160.0, "U/L", "Pancreatic Panel",
         "Pancreatitis", "Digestive Enzymes", "Pancrelipase"),
        ("Serum Alpha Amylase (Salivary)", 25.0, 125.0, "U/L", "Pancreatic Panel",
         "Pancreatitis", "Digestive Enzymes", "Pancrelipase, Omeprazole, Ranitidine"),
        ("Serum Lipase Isoenzyme", 0.0, 160.0, "U/L", "Pancreatic Panel",
         "Pancreatitis", "Digestive Enzymes", "Pancrelipase, Omeprazole"),

        # ===== PROTEIN PANEL =====
        ("Serum Alpha-2 Macroglobulin", 1.5, 3.5, "g/L", "Protein Panel",
         "Liver Disease", "Hepatic Therapy", "Silymarin, Ursodeoxycholic Acid"),
        ("Serum Beta Globulin", 0.7, 1.2, "g/dL", "Protein Panel",
         "Protein Imbalance", "Nutritional Therapy", "Albumin Infusion, Multivitamins, Amino Acids"),
        ("Serum Gamma Globulin", 0.6, 1.6, "g/dL", "Protein Panel",
         "Immune Disorder", "Immunotherapy", "IVIG, Prednisolone, Azathioprine"),

        # ===== THYROID PANEL =====
        ("Anti-Thyroglobulin Antibody", 0.0, 40.0, "IU/mL", "Thyroid Panel",
         "Autoimmune Thyroid Disease", "Thyroid Management", "Levothyroxine, Methimazole"),
        ("Anti-TPO Antibodies", 0.0, 35.0, "IU/mL", "Thyroid Panel",
         "Autoimmune Thyroiditis (Hashimoto's)", "Thyroid Hormone Therapy", "Levothyroxine, Selenium Supplements"),
        ("Anti-TPO Antibody", 0.0, 35.0, "IU/mL", "Thyroid Panel",
         "Autoimmune Thyroiditis", "Thyroid Hormones", "Levothyroxine, Methimazole"),
        ("Free T3", 2.3, 4.2, "pg/mL", "Thyroid Panel",
         "Thyroid Disorder", "Antithyroid Drugs", "Methimazole"),
        ("Free T3 (FT3)", 2.3, 4.2, "pg/mL", "Thyroid Panel",
         "Hyperthyroidism", "Anti-Thyroid Drugs", "Methimazole, Propylthiouracil, Carbimazole"),
        ("Free T4", 0.8, 1.8, "ng/dL", "Thyroid Panel",
         "Thyroid Disorder", "Thyroid Hormones", "Levothyroxine"),
        ("Free T4 (FT4)", 0.8, 1.8, "ng/dL", "Thyroid Panel",
         "Hypothyroidism / Hyperthyroidism", "Thyroid Replacement Therapy", "Levothyroxine, Liothyronine"),
        ("Reverse T3 (rT3)", 9.0, 24.0, "ng/dL", "Thyroid Panel",
         "Thyroid Conversion Disorder", "Hormone Regulation Therapy", "Levothyroxine, Liothyronine"),
        ("Serum Anti-Thyroglobulin", 0.0, 40.0, "IU/mL", "Thyroid Panel",
         "Autoimmune Thyroid Disease", "Thyroid Therapy", "Levothyroxine, Methimazole"),
        ("Thyroglobulin", 3.0, 40.0, "ng/mL", "Thyroid Panel",
         "Thyroid Cancer / Thyroid Tissue Damage", "Oncology / Thyroid Therapy", "Levothyroxine, Radioactive Iodine"),
        ("Thyroxine Binding Globulin (TBG)", 13.0, 39.0, "µg/mL", "Thyroid Panel",
         "Hormone Transport Disorder", "Thyroid Regulation", "Levothyroxine"),
        ("Total T3", 80.0, 200.0, "ng/dL", "Thyroid Panel",
         "Thyroid Dysfunction", "Thyroid Hormone Therapy", "Levothyroxine, Liothyronine"),
        ("Total T4", 5.0, 12.0, "µg/dL", "Thyroid Panel",
         "Thyroid Dysfunction", "Thyroid Replacement Therapy", "Levothyroxine"),
        ("TRAb (TSH Receptor Antibody)", 0.0, 1.5, "IU/L", "Thyroid Panel",
         "Graves Disease", "Anti-Thyroid Drugs", "Methimazole, Carbimazole"),
        ("TSH", 0.4, 4.0, "mIU/L", "Thyroid Panel",
         "Hypothyroidism / Hyperthyroidism", "Thyroid Hormones", "Levothyroxine"),
        ("TSI (Thyroid Stimulating Immunoglobulin)", 0.0, 1.3, "Index", "Thyroid Panel",
         "Graves Disease", "Anti-Thyroid Drugs", "Methimazole, Propylthiouracil, Beta Blockers"),

        # ===== TOXICOLOGY PANEL =====
        ("Serum Arsenic", 0.0, 50.0, "µg/L", "Toxicology Panel",
         "Arsenic Poisoning", "Chelation Therapy", "Dimercaprol, DMSA"),
        ("Serum Carboxyhemoglobin", 0.0, 5.0, "%", "Toxicology Panel",
         "Carbon Monoxide Poisoning", "Oxygen Therapy", "100% Oxygen, Hyperbaric Oxygen"),
        ("Serum Lead", 0.0, 5.0, "µg/dL", "Toxicology Panel",
         "Lead Poisoning", "Chelation Therapy", "EDTA, Dimercaprol, Succimer"),
        ("Serum Mercury", 0.0, 10.0, "µg/L", "Toxicology Panel",
         "Mercury Toxicity", "Chelation Therapy", "DMSA, Dimercaprol"),

        # ===== TRACE ELEMENTS =====
        ("Serum Copper", 70.0, 140.0, "µg/dL", "Trace Elements",
         "Wilson Disease", "Chelation Therapy", "Penicillamine, Trientine"),
        ("Serum Manganese", 4.0, 15.0, "µg/L", "Trace Elements",
         "Manganese Toxicity", "Chelation Therapy", "EDTA Therapy"),
        ("Serum Selenium", 70.0, 150.0, "µg/L", "Trace Elements",
         "Selenium Deficiency", "Supplement Therapy", "Selenium Tablets, Multivitamins"),
        ("Serum Zinc", 70.0, 120.0, "µg/dL", "Trace Elements",
         "Zinc Deficiency", "Supplement Therapy", "Zinc Sulfate, Multivitamins"),

        # ===== TUMOR MARKER =====
        ("Alpha Fetoprotein", 0.0, 10.0, "ng/mL", "Tumor Marker",
         "Liver Cancer Risk", "Oncology Drugs", "Sorafenib, Lenvatinib"),
        ("CA 19-9", 0.0, 37.0, "U/mL", "Tumor Marker",
         "Pancreatic Cancer Risk", "Chemotherapy", "Gemcitabine, FOLFIRINOX"),
        ("CA-125", 0.0, 35.0, "U/mL", "Tumor Marker",
         "Ovarian Cancer Risk", "Chemotherapy", "Paclitaxel, Carboplatin"),
        ("Serum Beta-2 Microglobulin", 0.7, 1.8, "mg/L", "Tumor Marker",
         "Multiple Myeloma", "Chemotherapy", "Bortezomib, Lenalidomide"),
        ("Serum CA 15-3", 0.0, 30.0, "U/mL", "Tumor Marker",
         "Breast Cancer", "Chemotherapy", "Trastuzumab, Paclitaxel"),
        ("Serum CEA", 0.0, 5.0, "ng/mL", "Tumor Marker",
         "Colon Cancer", "Oncology Drugs", "Capecitabine, Oxaliplatin"),
        ("Serum Prostate Acid Phosphatase", 0.0, 3.5, "ng/mL", "Tumor Marker",
         "Prostate Cancer", "Oncology Drugs", "Bicalutamide, Leuprolide, Docetaxel"),

        # ===== VITAMIN PANEL =====
        ("Serum Beta-Carotene", 50.0, 300.0, "µg/dL", "Vitamin Panel",
         "Vitamin A Deficiency", "Vitamin Supplements", "Retinol, Multivitamins"),
        ("Serum Biotin", 200.0, 900.0, "ng/L", "Vitamin Panel",
         "Biotin Deficiency", "Supplement Therapy", "Biotin Supplements"),
        ("Serum Folate", 2.0, 20.0, "ng/mL", "Vitamin Panel",
         "Folate Deficiency", "Vitamin Therapy", "Folic Acid, Multivitamins"),
        ("Serum Retinol", 20.0, 60.0, "µg/dL", "Vitamin Panel",
         "Vitamin A Deficiency", "Vitamin Therapy", "Retinol, Multivitamins"),
        ("Serum Vitamin E", 5.0, 20.0, "mg/L", "Vitamin Panel",
         "Vitamin E Deficiency", "Antioxidant Therapy", "Vitamin E Capsules, Multivitamins"),
        ("Serum Vitamin K", 0.2, 3.2, "ng/mL", "Vitamin Panel",
         "Bleeding Disorder", "Vitamin Therapy", "Vitamin K1, Phytonadione"),
        ("Vitamin B12", 200.0, 900.0, "pg/mL", "Vitamin Panel",
         "B12 Deficiency", "Vitamin Supplements", "Cyanocobalamin"),
        ("Vitamin D", 20.0, 50.0, "ng/mL", "Vitamin Panel",
         "Vitamin D Deficiency", "Vitamin D Supplements", "Cholecalciferol"),
    ]

    sql = """
        INSERT INTO lab_parameters (parameter_name, min_value, max_value, unit, category, condition_if_abnormal, drug_category, example_drugs) 
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    """

    cursor.executemany(sql, data)
    conn.commit()
    print(f"Inserted {cursor.rowcount} parameters successfully.")

    conn.close()

if __name__ == "__main__":
    try:
        seed_db()
    except Exception as e:
        print(f"Error: {e}")
